//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletWasabi.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WalletWasabi.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient participants, retrying....
        /// </summary>
        public static string AbortedNotEnoughAlicesMessage {
            get {
                return ResourceManager.GetString("AbortedNotEnoughAlicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Ginger Wallet&apos;s current info.
        /// </summary>
        public static string AboutViewModelCaption {
            get {
                return ResourceManager.GetString("AboutViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About, Software, Version, Source, Code, Github, Website, Coordinator, Stats, Tor, Onion, User, Support, Bug, Report, FAQ, Questions, Docs, Documentation, License, Advanced, Information, Hardware, Wallet.
        /// </summary>
        public static string AboutViewModelKeywords {
            get {
                return ResourceManager.GetString("AboutViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Ginger Wallet.
        /// </summary>
        public static string AboutViewModelTitle {
            get {
                return ResourceManager.GetString("AboutViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, connect, import or recover.
        /// </summary>
        public static string AddWalletPageViewModelCaption {
            get {
                return ResourceManager.GetString("AddWalletPageViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet, Add, Create, New, Recover, Import, Connect, Hardware, ColdCard, Trezor, Ledger.
        /// </summary>
        public static string AddWalletPageViewModelKeywords {
            get {
                return ResourceManager.GetString("AddWalletPageViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wallet.
        /// </summary>
        public static string AddWalletPageViewModelTitle {
            get {
                return ResourceManager.GetString("AddWalletPageViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymity score target.
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewAnonTargetText {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewAnonTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum anonymity score for a coin to be considered private..
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewAnonTargetTooltip {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewAnonTargetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin time preference.
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewCoinJoinTimePrefText {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewCoinJoinTimePrefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only coinjoin when the fee rate is below the median of this time period..
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewCoinJoinTimePrefToolTip {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewCoinJoinTimePrefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red coin isolation.
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewRedcoinText {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewRedcoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allow a single coin with anonymity score 1 into coinjoin registration..
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewRedcoinToolTip {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewRedcoinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe fee rate.
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewSafeFeeText {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewSafeFeeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always coinjoin when the fee rate is below this value (has precedence over Coinjoin time preference)..
        /// </summary>
        public static string AdvancedCoinjoinOptionsViewSafeFeeToolTip {
            get {
                return ResourceManager.GetString("AdvancedCoinjoinOptionsViewSafeFeeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage advanced settings.
        /// </summary>
        public static string AdvancedSettingsTabViewModelCaption {
            get {
                return ResourceManager.GetString("AdvancedSettingsTabViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings, Advanced, Enable, GPU.
        /// </summary>
        public static string AdvancedSettingsTabViewModelKeywords {
            get {
                return ResourceManager.GetString("AdvancedSettingsTabViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedSettingsTabViewModelTitle {
            get {
                return ResourceManager.GetString("AdvancedSettingsTabViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurray! All your funds are private!.
        /// </summary>
        public static string AllPrivateMessage {
            get {
                return ResourceManager.GetString("AllPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start coinjoin.
        /// </summary>
        public static string AutomaticallyStartCoinjoin {
            get {
                return ResourceManager.GetString("AutomaticallyStartCoinjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting connection.
        /// </summary>
        public static string BackendNotConnected {
            get {
                return ResourceManager.GetString("BackendNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Bitcoin settings.
        /// </summary>
        public static string BitcoinTabSettingsViewModelCaption {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings, Bitcoin, Network, Main, TestNet, RegTest, Run, Node, Core, Knots, Version, Startup, P2P, Endpoint, Dust, Threshold, BTC.
        /// </summary>
        public static string BitcoinTabSettingsViewModelKeywords {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin.
        /// </summary>
        public static string BitcoinTabSettingsViewModelTitle {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast your transaction here.
        /// </summary>
        public static string BroadcasterViewModelCaption {
            get {
                return ResourceManager.GetString("BroadcasterViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Id, Input, Output, Amount, Network, Fee, Count, BTC, Signed, Paste, Import, Broadcast, Transaction.
        /// </summary>
        public static string BroadcasterViewModelKeywords {
            get {
                return ResourceManager.GetString("BroadcasterViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcaster.
        /// </summary>
        public static string BroadcasterViewModelTitle {
            get {
                return ResourceManager.GetString("BroadcasterViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Ginger Wallet&apos;s GitHub issues website.
        /// </summary>
        public static string BugReportLinkViewModelCaption {
            get {
                return ResourceManager.GetString("BugReportLinkViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support, Website, Bug, Report.
        /// </summary>
        public static string BugReportLinkViewModelKeywords {
            get {
                return ResourceManager.GetString("BugReportLinkViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        public static string BugReportLinkViewModelTitle {
            get {
                return ResourceManager.GetString("BugReportLinkViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Transaction.
        /// </summary>
        public static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin.
        /// </summary>
        public static string Coinjoin {
            get {
                return ResourceManager.GetString("Coinjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin in progress.
        /// </summary>
        public static string CoinJoinInProgress {
            get {
                return ResourceManager.GetString("CoinJoinInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasabi takes care of your financial privacy by automatically starting to coinjoin all your funds for a fixed 0.3% coordination fee + the mining fees. Select a coinjoin strategy that fits you best!.
        /// </summary>
        public static string CoinJoinProfilesCaption {
            get {
                return ResourceManager.GetString("CoinJoinProfilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin Strategy.
        /// </summary>
        public static string CoinJoinProfilesViewModelTitle {
            get {
                return ResourceManager.GetString("CoinJoinProfilesViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin Settings.
        /// </summary>
        public static string CoinjoinSettings {
            get {
                return ResourceManager.GetString("CoinjoinSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin strategy:.
        /// </summary>
        public static string CoinjoinStrategy {
            get {
                return ResourceManager.GetString("CoinjoinStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Only loaded wallets can be selected..
        /// </summary>
        public static string CoinjoinToOtherWalletRestrictions1 {
            get {
                return ResourceManager.GetString("CoinjoinToOtherWalletRestrictions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Coins from the coinjoin transaction will be received by this wallet. However, this setting resets after Ginger restarts..
        /// </summary>
        public static string CoinjoinToOtherWalletRestrictions2 {
            get {
                return ResourceManager.GetString("CoinjoinToOtherWalletRestrictions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The selected wallet cannot be changed when a coinjoin is in progress..
        /// </summary>
        public static string CoinjoinToOtherWalletRestrictions3 {
            get {
                return ResourceManager.GetString("CoinjoinToOtherWalletRestrictions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin to this wallet:.
        /// </summary>
        public static string CoinjoinToThisWallet {
            get {
                return ResourceManager.GetString("CoinjoinToThisWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some funds are rejected from coinjoining.
        /// </summary>
        public static string CoinsRejectedMessage {
            get {
                return ResourceManager.GetString("CoinsRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordination fee rate was too high.
        /// </summary>
        public static string CoordinationFeeRateTooHighMessage {
            get {
                return ResourceManager.GetString("CoordinationFeeRateTooHighMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Amount.
        /// </summary>
        public static string CopyAmount {
            get {
                return ResourceManager.GetString("CopyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Label.
        /// </summary>
        public static string CopyLabel {
            get {
                return ResourceManager.GetString("CopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Transaction ID.
        /// </summary>
        public static string CopyTransactionId {
            get {
                return ResourceManager.GetString("CopyTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting auto-start of coinjoin.
        /// </summary>
        public static string CountDownMessage {
            get {
                return ResourceManager.GetString("CountDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discreet Mode.
        /// </summary>
        public static string DiscreetMode {
            get {
                return ResourceManager.GetString("DiscreetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Ginger Wallet&apos;s FAQ website.
        /// </summary>
        public static string DocsLinkViewModelCaption {
            get {
                return ResourceManager.GetString("DocsLinkViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User, Support, Website, Docs, Documentation, Guide.
        /// </summary>
        public static string DocsLinkViewModelKeywords {
            get {
                return ResourceManager.GetString("DocsLinkViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide/FAQ.
        /// </summary>
        public static string DocsLinkViewModelTitle {
            get {
                return ResourceManager.GetString("DocsLinkViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For savers. Only participates in coinjoins during the cheapest parts of the week..
        /// </summary>
        public static string EconomicCoinJoinProfileDescription {
            get {
                return ResourceManager.GetString("EconomicCoinJoinProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Costs.
        /// </summary>
        public static string EconomicCoinJoinProfileTitle {
            get {
                return ResourceManager.GetString("EconomicCoinJoinProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Coins.
        /// </summary>
        public static string ExcludeCoins {
            get {
                return ResourceManager.GetString("ExcludeCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting valid conditions.
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettingsTabViewModelCaption {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings, General, Bitcoin, Dark, Mode, Run, Wasabi, Computer, System, Start, Background, Close, Auto, Copy, Paste, Addresses, Custom, Change, Address, Fee, Display, Format, BTC, sats, browser.
        /// </summary>
        public static string GeneralSettingsTabViewModelKeywords {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettingsTabViewModelTitle {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string HelpAndSupport {
            get {
                return ResourceManager.GetString("HelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting other participants.
        /// </summary>
        public static string InputRegistrationMessage {
            get {
                return ResourceManager.GetString("InputRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display terms and conditions.
        /// </summary>
        public static string LegalDocumentsViewModelCaption {
            get {
                return ResourceManager.GetString("LegalDocumentsViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Legal, Document, Terms, Conditions, Privacy, Policy, Statement.
        /// </summary>
        public static string LegalDocumentsViewModelKeywords {
            get {
                return ResourceManager.GetString("LegalDocumentsViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Document.
        /// </summary>
        public static string LegalDocumentsViewModelTitle {
            get {
                return ResourceManager.GetString("LegalDocumentsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Downloading and processing Bitcoin network data.
        /// </summary>
        public static string LoadingViewDownloadText {
            get {
                return ResourceManager.GetString("LoadingViewDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% completed.
        /// </summary>
        public static string LoadingViewModelPercentCompleted {
            get {
                return ResourceManager.GetString("LoadingViewModelPercentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} remaining.
        /// </summary>
        public static string LoadingViewModelTimeRemaining {
            get {
                return ResourceManager.GetString("LoadingViewModelTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This process will be longer on first launch, with larger wallets, or after long gaps between synchronizations..
        /// </summary>
        public static string LoadingViewProcessLonger {
            get {
                return ResourceManager.GetString("LoadingViewProcessLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasabi does this without any third party knowing about your balance and financial activity..
        /// </summary>
        public static string LoadingViewThirdparty {
            get {
                return ResourceManager.GetString("LoadingViewThirdparty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin Strategy Settings.
        /// </summary>
        public static string ManualCoinJoinProfileDialogTitle {
            get {
                return ResourceManager.GetString("ManualCoinJoinProfileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ManualCoinJoinProfileTitle {
            get {
                return ResourceManager.GetString("ManualCoinJoinProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining fee rate was too high.
        /// </summary>
        public static string MiningFeeRateTooHighMessage {
            get {
                return ResourceManager.GetString("MiningFeeRateTooHighMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min input count was too low.
        /// </summary>
        public static string MinInputCountTooLowMessage {
            get {
                return ResourceManager.GetString("MinInputCountTooLowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category.
        /// </summary>
        public static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds eligible for coinjoin.
        /// </summary>
        public static string NoCoinsEligibleToMixMessage {
            get {
                return ResourceManager.GetString("NoCoinsEligibleToMixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only excluded funds are available.
        /// </summary>
        public static string OnlyExcludedCoinsAvailableMessage {
            get {
                return ResourceManager.GetString("OnlyExcludedCoinsAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only immature funds are available.
        /// </summary>
        public static string OnlyImmatureCoinsAvailableMessage {
            get {
                return ResourceManager.GetString("OnlyImmatureCoinsAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse, Open, Config, File.
        /// </summary>
        public static string OpenConfigFileViewModelKeywords {
            get {
                return ResourceManager.GetString("OpenConfigFileViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config File.
        /// </summary>
        public static string OpenConfigFileViewModelTitle {
            get {
                return ResourceManager.GetString("OpenConfigFileViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse, Open, Data, Folder.
        /// </summary>
        public static string OpenDataFolderViewModelKeywords {
            get {
                return ResourceManager.GetString("OpenDataFolderViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Folder.
        /// </summary>
        public static string OpenDataFolderViewModelTitle {
            get {
                return ResourceManager.GetString("OpenDataFolderViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in the browser.
        /// </summary>
        public static string OpenInTheBrowser {
            get {
                return ResourceManager.GetString("OpenInTheBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse, Open, Logs.
        /// </summary>
        public static string OpenLogsViewModelKeywords {
            get {
                return ResourceManager.GetString("OpenLogsViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string OpenLogsViewModelTitle {
            get {
                return ResourceManager.GetString("OpenLogsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string OpenPasswordBoxWatermark {
            get {
                return ResourceManager.GetString("OpenPasswordBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse, Open, Tor, Logs.
        /// </summary>
        public static string OpenTorLogsViewModelKeywords {
            get {
                return ResourceManager.GetString("OpenTorLogsViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor Logs.
        /// </summary>
        public static string OpenTorLogsViewModelTitle {
            get {
                return ResourceManager.GetString("OpenTorLogsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse, Open, Wallet, Folder.
        /// </summary>
        public static string OpenWalletsFolderViewModelKeywords {
            get {
                return ResourceManager.GetString("OpenWalletsFolderViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Folder.
        /// </summary>
        public static string OpenWalletsFolderViewModelTitle {
            get {
                return ResourceManager.GetString("OpenWalletsFolderViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin is paused.
        /// </summary>
        public static string PauseMessage {
            get {
                return ResourceManager.GetString("PauseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin may be uneconomical.
        /// </summary>
        public static string PlebStopMessage {
            get {
                return ResourceManager.GetString("PlebStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more funds or press Play to bypass.
        /// </summary>
        public static string PlebStopMessageBelow {
            get {
                return ResourceManager.GetString("PlebStopMessageBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop coinjoin threshold.
        /// </summary>
        public static string PlebStopThreshold {
            get {
                return ResourceManager.GetString("PlebStopThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin will automatically stop if the wallet balance is less than this..
        /// </summary>
        public static string PlebStopToolTip {
            get {
                return ResourceManager.GetString("PlebStopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Play to start.
        /// </summary>
        public static string PressPlayToStartMessage {
            get {
                return ResourceManager.GetString("PressPlayToStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice of the paranoid. Optimizes for privacy at all costs..
        /// </summary>
        public static string PrivateCoinJoinProfileDescription {
            get {
                return ResourceManager.GetString("PrivateCoinJoinProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Privacy.
        /// </summary>
        public static string PrivateCoinJoinProfileTitle {
            get {
                return ResourceManager.GetString("PrivateCoinJoinProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSBT workflow.
        /// </summary>
        public static string PSBTworkflow {
            get {
                return ResourceManager.GetString("PSBTworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping a round for better privacy.
        /// </summary>
        public static string RandomlySkippedRoundMessage {
            get {
                return ResourceManager.GetString("RandomlySkippedRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round ended, awaiting next round.
        /// </summary>
        public static string RoundFinishedMessage {
            get {
                return ResourceManager.GetString("RoundFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin successful! Continuing....
        /// </summary>
        public static string RoundSucceedMessage {
            get {
                return ResourceManager.GetString("RoundSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search settings / advanced features.
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage security settings.
        /// </summary>
        public static string SecuritySettingsTabViewModelCaption {
            get {
                return ResourceManager.GetString("SecuritySettingsTabViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security, Settings, 2FA, Two-Factor, Authentication, Two, Factor.
        /// </summary>
        public static string SecuritySettingsTabViewModelKeywords {
            get {
                return ResourceManager.GetString("SecuritySettingsTabViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecuritySettingsTabViewModelTitle {
            get {
                return ResourceManager.GetString("SecuritySettingsTabViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server did not give remix fee exemption.
        /// </summary>
        public static string ServerDidNotGiveFeeExemptionMessage {
            get {
                return ResourceManager.GetString("ServerDidNotGiveFeeExemptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage appearance, privacy and other settings.
        /// </summary>
        public static string SettingsPageViewModelCaption {
            get {
                return ResourceManager.GetString("SettingsPageViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings, General, User, Interface, Advanced.
        /// </summary>
        public static string SettingsPageViewModelKeywords {
            get {
                return ResourceManager.GetString("SettingsPageViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageViewModelTitle {
            get {
                return ResourceManager.GetString("SettingsPageViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Up Transaction.
        /// </summary>
        public static string SpeedUpTransaction {
            get {
                return ResourceManager.GetString("SpeedUpTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting things done. Geared towards speed and convenience..
        /// </summary>
        public static string SpeedyCoinJoinProfileDescription {
            get {
                return ResourceManager.GetString("SpeedyCoinJoinProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Speed.
        /// </summary>
        public static string SpeedyCoinJoinProfileTitle {
            get {
                return ResourceManager.GetString("SpeedyCoinJoinProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin has stopped.
        /// </summary>
        public static string StoppedMessage {
            get {
                return ResourceManager.GetString("StoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor authentication is disabled. Enable it in the Setting for greater protection..
        /// </summary>
        public static string TwoFactorDisabledWarnMessage {
            get {
                return ResourceManager.GetString("TwoFactorDisabledWarnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string TwoFactorDisabledWarnMessageOpenSettings {
            get {
                return ResourceManager.GetString("TwoFactorDisabledWarnMessageOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting cheaper coinjoins.
        /// </summary>
        public static string UneconomicalRoundMessage {
            get {
                return ResourceManager.GetString("UneconomicalRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting closure of send dialog.
        /// </summary>
        public static string UserInSendWorkflowMessage {
            get {
                return ResourceManager.GetString("UserInSendWorkflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Ginger Wallet&apos;s user support website
        ///.
        /// </summary>
        public static string UserSupportViewModelCaption {
            get {
                return ResourceManager.GetString("UserSupportViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User, Support, Website.
        /// </summary>
        public static string UserSupportViewModelKeywords {
            get {
                return ResourceManager.GetString("UserSupportViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Support.
        /// </summary>
        public static string UserSupportViewModelTitle {
            get {
                return ResourceManager.GetString("UserSupportViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting the blame round.
        /// </summary>
        public static string WaitingForBlameRoundMessage {
            get {
                return ResourceManager.GetString("WaitingForBlameRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting confirmed funds.
        /// </summary>
        public static string WaitingForConfirmedFunds {
            get {
                return ResourceManager.GetString("WaitingForConfirmedFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for response.
        /// </summary>
        public static string WaitingForResponse {
            get {
                return ResourceManager.GetString("WaitingForResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting coinjoin.
        /// </summary>
        public static string WaitingMessage {
            get {
                return ResourceManager.GetString("WaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitingRoundMessage.
        /// </summary>
        public static string WaitingRoundMessage {
            get {
                return ResourceManager.GetString("WaitingRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string WalletAutomatic {
            get {
                return ResourceManager.GetString("WalletAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE.
        /// </summary>
        public static string WalletBalance {
            get {
                return ResourceManager.GetString("WalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display wallet coinjoin settings.
        /// </summary>
        public static string WalletCoinJoinSettingsViewModelCaption {
            get {
                return ResourceManager.GetString("WalletCoinJoinSettingsViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet, Settings.
        /// </summary>
        public static string WalletCoinJoinSettingsViewModelKeywords {
            get {
                return ResourceManager.GetString("WalletCoinJoinSettingsViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinjoin Settings.
        /// </summary>
        public static string WalletCoinJoinSettingsViewModelTitle {
            get {
                return ResourceManager.GetString("WalletCoinJoinSettingsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Coins.
        /// </summary>
        public static string WalletCoins {
            get {
                return ResourceManager.GetString("WalletCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCHANGE RATE.
        /// </summary>
        public static string WalletExchangeRate {
            get {
                return ResourceManager.GetString("WalletExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Info.
        /// </summary>
        public static string WalletInfo {
            get {
                return ResourceManager.GetString("WalletInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Control.
        /// </summary>
        public static string WalletManualControl {
            get {
                return ResourceManager.GetString("WalletManualControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVACY PROGRESS.
        /// </summary>
        public static string WalletPrivacyProgress {
            get {
                return ResourceManager.GetString("WalletPrivacyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string WalletReceive {
            get {
                return ResourceManager.GetString("WalletReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string WalletSend {
            get {
                return ResourceManager.GetString("WalletSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Settings.
        /// </summary>
        public static string WalletSettings {
            get {
                return ResourceManager.GetString("WalletSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display wallet settings.
        /// </summary>
        public static string WalletSettingsViewModelCaption {
            get {
                return ResourceManager.GetString("WalletSettingsViewModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet, Settings.
        /// </summary>
        public static string WalletSettingsViewModelKeywords {
            get {
                return ResourceManager.GetString("WalletSettingsViewModelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Settings.
        /// </summary>
        public static string WalletSettingsViewModelTitle {
            get {
                return ResourceManager.GetString("WalletSettingsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Stats.
        /// </summary>
        public static string WalletStats {
            get {
                return ResourceManager.GetString("WalletStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you checked your wallet backup?.
        /// </summary>
        public static string WalletToolsCheckBackup {
            get {
                return ResourceManager.GetString("WalletToolsCheckBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passphrase is also required to restore your wallet, do not forget it..
        /// </summary>
        public static string WalletToolsDoNotForget {
            get {
                return ResourceManager.GetString("WalletToolsDoNotForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended that you verify your wallet Recovery Words from time to time..
        /// </summary>
        public static string WalletToolsRecommend {
            get {
                return ResourceManager.GetString("WalletToolsRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Recovery Words.
        /// </summary>
        public static string WalletToolsVerifyRecoveryWords {
            get {
                return ResourceManager.GetString("WalletToolsVerifyRecoveryWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string WalletTransactions {
            get {
                return ResourceManager.GetString("WalletTransactions", resourceCulture);
            }
        }
    }
}
