name: UnitTests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore --configuration Release --filter "UnitTests" --logger "console;verbosity=detailed"
        continue-on-error: true # Continue even if tests fail to allow other OSs to complete

      - name: Check test results
        if: always() # Ensure this step runs regardless of the test result
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed on ${{ matrix.os }}"
          fi
          
      - name: Fail the job if any OS fails
        if: failure()
        run: exit 1
